;;; eradio-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from eradio.el

(defvar eradio-channels 'nil "\
Eradio's radio channels.")
(custom-autoload 'eradio-channels "eradio" t)
(autoload 'eradio-stop "eradio" "\
Stop the radio player." t)
(autoload 'eradio-toggle "eradio" "\
Toggle the radio player." t)
(autoload 'eradio-play "eradio" "\
Play a radio channel, do what I mean.

(fn &optional URL)" t)
(register-definition-prefixes "eradio" '("eradio-"))

;;; End of scraped data

(provide 'eradio-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eradio-autoloads.el ends here
