# alacritty.toml
[window]
opacity = 0.8                # Slightly opaque background
decorations = "none"          # No window decorations
blur = false                  # No background blur

[font]
size = 15.0                   # Font size
normal.family = "JetBrains mono"     # Font family

[colors]
# Minimal Vague2k color scheme (4 colors, no bright)
primary.background = "#000000" # Dark background
primary.foreground = "#e4e4e4" # Light foreground

