;;; denote-markdown-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from denote-markdown.el

(autoload 'denote-markdown-convert-links-to-file-paths "denote-markdown" "\
Convert denote: links to file paths.
Ignore all other link types.  Also ignore links that do not
resolve to a file in the variable `denote-directory'.

With optional ABSOLUTE, format paths as absolute, otherwise do them
relative to the variable `denote-directory'.

(fn &optional ABSOLUTE)" '(markdown-mode))
(autoload 'denote-markdown-convert-links-to-denote-type "denote-markdown" "\
Convert generic file links to denote: links in the current Markdown buffer.
Ignore all other link types.  Also ignore file links that do not point
to a file with a Denote file name.

Also see `denote-markdown-convert-obsidian-links-to-denote-type'." '(markdown-mode))
(autoload 'denote-markdown-convert-links-to-obsidian-type "denote-markdown" "\
Convert denote: links to Obsidian-style file paths.
Ignore all other link types.  Also ignore links that do not
resolve to a file in the variable `denote-directory'." '(markdown-mode))
(autoload 'denote-markdown-convert-obsidian-links-to-denote-type "denote-markdown" "\
Convert Obsidian-style links to denote: links in the current Markdown buffer.
Ignore all other link types.  Also ignore file links that do not point
to a file with a Denote file name.

Also see `denote-markdown-convert-links-to-denote-type'." '(markdown-mode))
(register-definition-prefixes "denote-markdown" '("denote-markdown--get-regexp"))

;;; End of scraped data

(provide 'denote-markdown-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-markdown-autoloads.el ends here
