#!/usr/bin/env bash

i3-msg "workspace 2"

emacs &
st &
firefox --new-window &

sleep 2

i3-msg '[class="Emacs"] focus'
i3-msg 'layout tabbed'

i3-msg '[class="st-256color"] focus'
i3-msg 'layout tabbed'

i3-msg '[class="Firefox"] focus'
i3-msg 'layout tabbed'

i3-msg '[class="Emacs"] focus'

