#!/usr/bin/env bash
WALLPAPER_DIR="$HOME/devenv/wallpaper/anime/"
INTERVAL=30
if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Directory $WALLPAPER_DIR not found!"
    exit 1
fi
mapfile -t wallpapers < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | sort)
if [ ${#wallpapers[@]} -eq 0 ]; then
    echo "No image files found in $WALLPAPER_DIR."
    exit 1
fi
while true; do
    for wallpaper in "${wallpapers[@]}"; do
        feh --bg-scale "$wallpaper"
        echo "Set wallpaper: $wallpaper"
        sleep "$INTERVAL"
    done
done

