#!/usr/bin/env bash

exec --no-startup-id nm-applet
exec --no-startup-id dunst &
exec --no-startup-id blueman-applet
exec --no-startup-id picom --config ~/.config/picom.conf --experimental-backends
exec --no-startup-id xsetroot -cursor_name left_ptr
exec /user/bin/emacs --daemon
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
